/**
 * GENERATED by web/tools/build-docs.mjs — do not edit.
 *
 * Run `node web/tools/build-docs.mjs` after changing anything in docs/.
 * Committed so the API has no build-time dependency on the docs pipeline.
 */

export interface DocsEntry {
  /** Heading text, or the page name for a page-level entry. */
  title: string;
  /** Which document it is in, for display. */
  page: string;
  url: string;
  /** Page-level entries carry the sidebar blurb; headings do not. */
  blurb: string | null;
}

export const DOCS_INDEX: DocsEntry[] = [
  {
    "title": "Quickstart",
    "page": "Quickstart",
    "url": "https://docs.yappy.gg/quickstart/",
    "blurb": "A working bot in fifteen minutes, from token to button press."
  },
  {
    "title": "1. Create the bot",
    "page": "Quickstart",
    "url": "https://docs.yappy.gg/quickstart/#1-create-the-bot",
    "blurb": null
  },
  {
    "title": "2. Say hello",
    "page": "Quickstart",
    "url": "https://docs.yappy.gg/quickstart/#2-say-hello",
    "blurb": null
  },
  {
    "title": "3. Put it in a group",
    "page": "Quickstart",
    "url": "https://docs.yappy.gg/quickstart/#3-put-it-in-a-group",
    "blurb": null
  },
  {
    "title": "4. Send a card instead",
    "page": "Quickstart",
    "url": "https://docs.yappy.gg/quickstart/#4-send-a-card-instead",
    "blurb": null
  },
  {
    "title": "5. Declare a slash command",
    "page": "Quickstart",
    "url": "https://docs.yappy.gg/quickstart/#5-declare-a-slash-command",
    "blurb": null
  },
  {
    "title": "6. Hear about the world",
    "page": "Quickstart",
    "url": "https://docs.yappy.gg/quickstart/#6-hear-about-the-world",
    "blurb": null
  },
  {
    "title": "7. Post a button and press it",
    "page": "Quickstart",
    "url": "https://docs.yappy.gg/quickstart/#7-post-a-button-and-press-it",
    "blurb": null
  },
  {
    "title": "8. The one rule",
    "page": "Quickstart",
    "url": "https://docs.yappy.gg/quickstart/#8-the-one-rule",
    "blurb": null
  },
  {
    "title": "Where to go next",
    "page": "Quickstart",
    "url": "https://docs.yappy.gg/quickstart/#where-to-go-next",
    "blurb": null
  },
  {
    "title": "Building bots",
    "page": "Building bots",
    "url": "https://docs.yappy.gg/bots/",
    "blurb": "The bot platform in depth: embeds, components, commands, webhooks, permissions."
  },
  {
    "title": "Contents",
    "page": "Building bots",
    "url": "https://docs.yappy.gg/bots/#contents",
    "blurb": null
  },
  {
    "title": "1. Register a bot",
    "page": "Building bots",
    "url": "https://docs.yappy.gg/bots/#1-register-a-bot",
    "blurb": null
  },
  {
    "title": "2. Authenticate",
    "page": "Building bots",
    "url": "https://docs.yappy.gg/bots/#2-authenticate",
    "blurb": null
  },
  {
    "title": "3. Send messages",
    "page": "Building bots",
    "url": "https://docs.yappy.gg/bots/#3-send-messages",
    "blurb": null
  },
  {
    "title": "4. Embeds",
    "page": "Building bots",
    "url": "https://docs.yappy.gg/bots/#4-embeds",
    "blurb": null
  },
  {
    "title": "5. Buttons and interactions",
    "page": "Building bots",
    "url": "https://docs.yappy.gg/bots/#5-buttons-and-interactions",
    "blurb": null
  },
  {
    "title": "6. Slash commands",
    "page": "Building bots",
    "url": "https://docs.yappy.gg/bots/#6-slash-commands",
    "blurb": null
  },
  {
    "title": "7. The permission model, and the one rule",
    "page": "Building bots",
    "url": "https://docs.yappy.gg/bots/#7-the-permission-model-and-the-one-rule",
    "blurb": null
  },
  {
    "title": "8. Webhooks",
    "page": "Building bots",
    "url": "https://docs.yappy.gg/bots/#8-webhooks",
    "blurb": null
  },
  {
    "title": "9. Rate limits and etiquette",
    "page": "Building bots",
    "url": "https://docs.yappy.gg/bots/#9-rate-limits-and-etiquette",
    "blurb": null
  },
  {
    "title": "10. Reference",
    "page": "Building bots",
    "url": "https://docs.yappy.gg/bots/#10-reference",
    "blurb": null
  },
  {
    "title": "Bot authentication",
    "page": "Building bots",
    "url": "https://docs.yappy.gg/bots/#bot-authentication",
    "blurb": null
  },
  {
    "title": "Permission bits",
    "page": "Building bots",
    "url": "https://docs.yappy.gg/bots/#permission-bits",
    "blurb": null
  },
  {
    "title": "Button object",
    "page": "Building bots",
    "url": "https://docs.yappy.gg/bots/#button-object",
    "blurb": null
  },
  {
    "title": "Interaction response kinds",
    "page": "Building bots",
    "url": "https://docs.yappy.gg/bots/#interaction-response-kinds",
    "blurb": null
  },
  {
    "title": "Webhook headers",
    "page": "Building bots",
    "url": "https://docs.yappy.gg/bots/#webhook-headers",
    "blurb": null
  },
  {
    "title": "Asking yapper instead of reading this",
    "page": "Building bots",
    "url": "https://docs.yappy.gg/bots/#asking-yapper-instead-of-reading-this",
    "blurb": null
  },
  {
    "title": "First-party vs third-party",
    "page": "Building bots",
    "url": "https://docs.yappy.gg/bots/#first-party-vs-third-party",
    "blurb": null
  },
  {
    "title": "Bot API",
    "page": "Bot API",
    "url": "https://docs.yappy.gg/bot-api/",
    "blurb": "Every endpoint a bot token can call, grouped by what you are trying to do."
  },
  {
    "title": "Your application",
    "page": "Bot API",
    "url": "https://docs.yappy.gg/bot-api/#your-application",
    "blurb": null
  },
  {
    "title": "Conversations",
    "page": "Bot API",
    "url": "https://docs.yappy.gg/bot-api/#conversations",
    "blurb": null
  },
  {
    "title": "Messages",
    "page": "Bot API",
    "url": "https://docs.yappy.gg/bot-api/#messages",
    "blurb": null
  },
  {
    "title": "Reactions and pins",
    "page": "Bot API",
    "url": "https://docs.yappy.gg/bot-api/#reactions-and-pins",
    "blurb": null
  },
  {
    "title": "Commands and interactions",
    "page": "Bot API",
    "url": "https://docs.yappy.gg/bot-api/#commands-and-interactions",
    "blurb": null
  },
  {
    "title": "Polls",
    "page": "Bot API",
    "url": "https://docs.yappy.gg/bot-api/#polls",
    "blurb": null
  },
  {
    "title": "Webhook deliveries",
    "page": "Bot API",
    "url": "https://docs.yappy.gg/bot-api/#webhook-deliveries",
    "blurb": null
  },
  {
    "title": "What bots cannot do",
    "page": "Bot API",
    "url": "https://docs.yappy.gg/bot-api/#what-bots-cannot-do",
    "blurb": null
  },
  {
    "title": "Permissions",
    "page": "Permissions",
    "url": "https://docs.yappy.gg/permissions/",
    "blurb": "The bitfield, how it is computed, and the rule that governs every check."
  },
  {
    "title": "The rule",
    "page": "Permissions",
    "url": "https://docs.yappy.gg/permissions/#the-rule",
    "blurb": null
  },
  {
    "title": "On the wire",
    "page": "Permissions",
    "url": "https://docs.yappy.gg/permissions/#on-the-wire",
    "blurb": null
  },
  {
    "title": "The bits",
    "page": "Permissions",
    "url": "https://docs.yappy.gg/permissions/#the-bits",
    "blurb": null
  },
  {
    "title": "How a member's permissions are computed",
    "page": "Permissions",
    "url": "https://docs.yappy.gg/permissions/#how-a-member-s-permissions-are-computed",
    "blurb": null
  },
  {
    "title": "Checking someone else's permissions",
    "page": "Permissions",
    "url": "https://docs.yappy.gg/permissions/#checking-someone-else-s-permissions",
    "blurb": null
  },
  {
    "title": "Gating your own commands",
    "page": "Permissions",
    "url": "https://docs.yappy.gg/permissions/#gating-your-own-commands",
    "blurb": null
  },
  {
    "title": "Errors and limits",
    "page": "Errors and limits",
    "url": "https://docs.yappy.gg/errors/",
    "blurb": "The error envelope, every code, the rate limits, and how to retry safely."
  },
  {
    "title": "The envelope",
    "page": "Errors and limits",
    "url": "https://docs.yappy.gg/errors/#the-envelope",
    "blurb": null
  },
  {
    "title": "Codes",
    "page": "Errors and limits",
    "url": "https://docs.yappy.gg/errors/#codes",
    "blurb": null
  },
  {
    "title": "400 and 422, the request was wrong",
    "page": "Errors and limits",
    "url": "https://docs.yappy.gg/errors/#400-and-422-the-request-was-wrong",
    "blurb": null
  },
  {
    "title": "401, we do not know who you are",
    "page": "Errors and limits",
    "url": "https://docs.yappy.gg/errors/#401-we-do-not-know-who-you-are",
    "blurb": null
  },
  {
    "title": "403, we know, and no",
    "page": "Errors and limits",
    "url": "https://docs.yappy.gg/errors/#403-we-know-and-no",
    "blurb": null
  },
  {
    "title": "404, nothing here",
    "page": "Errors and limits",
    "url": "https://docs.yappy.gg/errors/#404-nothing-here",
    "blurb": null
  },
  {
    "title": "409, a conflict with what already is",
    "page": "Errors and limits",
    "url": "https://docs.yappy.gg/errors/#409-a-conflict-with-what-already-is",
    "blurb": null
  },
  {
    "title": "429, slow down",
    "page": "Errors and limits",
    "url": "https://docs.yappy.gg/errors/#429-slow-down",
    "blurb": null
  },
  {
    "title": "500 and 503, our fault",
    "page": "Errors and limits",
    "url": "https://docs.yappy.gg/errors/#500-and-503-our-fault",
    "blurb": null
  },
  {
    "title": "Rate limits",
    "page": "Errors and limits",
    "url": "https://docs.yappy.gg/errors/#rate-limits",
    "blurb": null
  },
  {
    "title": "Retrying safely",
    "page": "Errors and limits",
    "url": "https://docs.yappy.gg/errors/#retrying-safely",
    "blurb": null
  }
];

/** Error code to the one-line meaning published in docs/ERRORS.md. */
export const ERROR_HELP: Record<string, string> = {
  "bad_request": "Malformed in a way the schema did not catch",
  "validation_failed": "A field failed validation. details names the fields",
  "unsupported_media_type": "Wrong content type",
  "payload_too_large": "Body over the limit",
  "unprocessable": "Well formed, but not a thing that can be done",
  "edit_window_expired": "The message is too old to edit",
  "message_deleted": "The target message is gone",
  "unauthenticated": "Missing or unparseable credential",
  "token_expired": "Valid token, past its lifetime",
  "token_revoked": "Rotated, logged out, or the bot token was regenerated",
  "forbidden": "Not allowed, without a more specific reason",
  "missing_permission": "The permission bit is absent. details.permission names it",
  "blocked": "The other account has blocked this one",
  "privacy_restricted": "Their privacy settings do not allow this",
  "account_suspended": "The account is suspended. Reads still work, writes do not",
  "not_found": "No such thing",
  "not_a_member": "The conversation exists but you are not in it",
  "conflict": "The state does not permit this",
  "already_exists": "Duplicate of something unique, such as a handle",
  "already_a_member": "Already joined",
  "call_already_ended": "The call is over",
  "call_full": "The call is at capacity",
  "rate_limited": "Bucket empty. retryAfter is seconds",
  "slow_mode": "The conversation has slow mode on. retryAfter is seconds",
  "internal_error": "Unexpected. Safe to retry with backoff",
  "service_unavailable": "A dependency is down. Retry with backoff"
};

export const DOCS_BASE_URL = "https://docs.yappy.gg";
